### ISSUE TITLE
Confusion about the product. 

### ISSUE THREAD

**Issue by noSpamsPlease** [grandEL-dsouza/pwa-with-webdriverIO-and-nodejs-for-Browserstack-automated-test#1]
As a user I'm looking to test my website with it's PWA (Progressive Web App).

To test the website I use the Browserstack Automate product. 

The code provided here however is of the App-Automate product, should I not be testing this on Automate itself. 

Please help.

**Comment by grandEL-dsouza** [comment]
Hey @noSpamsPlease 

Thank you for raising your concern here. 

I would like to inform you that installing any Application is no permitted on the Browserstack Automate product due to certain restrictions. 

Hence this is a work around offered to user's to test their PWA on the App-Automate product as there is no restrictions to installing the Apps there. 

I hope this answers your query. 

Thanks.
